# Additive Control World Model Configuration
# This model separates action processing from visual/proprio processing
# to avoid gradient entanglement and improve planning stability

model:
  _target_: models.additive_control_world_model.AdditiveControlVWorldModel
  image_size: ${img_size}
  num_hist: ${num_hist}
  num_pred: ${num_pred}
  train_encoder: False
  train_predictor: True
  train_decoder: True
