defaults:
  - _self_
  - planner: cem
  # - override hydra/launcher: submitit_slurm
base_path: /projects/coreyc/coreyc_mp_jepa/graph_world_models/ejlaird/dino_wm/

hydra:
  run:
    dir: ${base_path}/plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
  sweep:
    dir: ${base_path}/plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
    subdir: ${hydra.job.num}

# model to load for planning
ckpt_base_path: /projects/coreyc/coreyc_mp_jepa/graph_world_models/ejlaird/dino_wm/checkpoints # put absolute path here. Checkpoints will be loaded from ${ckpt_base_path}/outputs
model_name: null
model_epoch: latest

seed: 99
n_evals: 10
goal_source: 'dset' # 'random_state' or 'dset' or 'random_action' 
goal_H: 5 # specifies how far away the goal is if goal_source is 'dset'
n_plot_samples: 10

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 2 # coeff base for weighting all frames. Only applies when mode == 'all'
  mode: last
