defaults:
  - _self_
  - planner: mpc_gd

base_path: /projects/coreyc/coreyc_mp_jepa/graph_world_models/ejlaird/dino_wm/

hydra:
  run:
    dir: ${base_path}/plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
  sweep:
    dir: ${base_path}/plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
    subdir: ${hydra.job.num}

# model to load for planning
ckpt_base_path: /lustre/smuexa01/client/users/ejlaird/dino_wm/checkpoints # put absolute path here. Checkpoints will be loaded from ${ckpt_base_path}/outputs
# ckpt_base_path: /projects/coreyc/coreyc_mp_jepa/graph_world_models/ejlaird/dino_wm/checkpoints # put absolute path here. Checkpoints will be loaded from ${ckpt_base_path}/outputs
model_name: 2025-10-30/09-55-08 # baseline
model_epoch: latest

seed: 99
n_evals: 10 
goal_source: 'random_state'
goal_H: 6
n_plot_samples: 10
K: null

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 0
  base: 0.5
  mode: all

planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: 10 
  n_taken_actions: 1
  sub_planner:
    target: planning.gd.GDPlanner
    horizon: 5
    action_noise: 0.003
    sample_type: 'randn' # 'zero' or 'randn'
    lr: 1 
    opt_steps: 100
    eval_every: 10
    optimizer_type: "sgd" # "sgd" or "adam"
    max_grad_norm: null
  name: mpc_gd
