defaults:
  - _self_
  - planner: mpc_cem

base_path: /projects/coreyc/coreyc_mp_jepa/graph_world_models/ejlaird/dino_wm/

hydra:
  run:
    dir: ${base_path}/plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
  sweep:
    dir: ${base_path}/plan_outputs/${now:%Y%m%d%H%M%S}_${replace_slash:${model_name}}_gH${goal_H}
    subdir: ${hydra.job.num}

# model to load for planning
ckpt_base_path: /lustre/smuexa01/client/users/ejlaird/dino_wm/checkpoints # put absolute path here. Checkpoints will be loaded from ${ckpt_base_path}/outputs
# ckpt_base_path: /projects/coreyc/coreyc_mp_jepa/graph_world_models/ejlaird/dino_wm/checkpoints # put absolute path here. Checkpoints will be loaded from ${ckpt_base_path}/outputs
model_name: null
model_epoch: latest

seed: 99
n_evals: 10 
goal_source: 'random_state'
: 5 
n_plot_samples: 4
K: null

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 0
  base: 2 
  mode: last

planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: null 
  n_taken_actions: 5
  sub_planner:
    target: planning.cem.CEMPlanner
    horizon: 5
    topk: 30
    num_samples: 300
    var_scale: 1
    opt_steps: 10
    eval_every: 5
  name: mpc_cem