_target_: models.additive_control_world_model.AdditiveControlVWorldModel
image_size: ${img_size}
num_hist: ${num_hist}
num_pred: ${num_pred}
train_encoder: False
train_predictor: True
train_decoder: True
