_target_: models.visual_world_model.VWorldModel
image_size: ${img_size}
num_hist: ${num_hist}
num_pred: ${num_pred}
train_encoder: False
train_predictor: True
train_decoder: True
decoder_loss_type: ${decoder_loss_type}
step_size: ${step_size}
use_cls_token: ${use_cls_token}