_target_: models.second_order_model.SecondOrderModel
image_size: ${img_size}
num_hist: ${num_hist}
num_pred: ${num_pred}
train_encoder: ${train_encoder}
train_predictor: ${train_predictor}
train_decoder: ${train_decoder}
decoder_loss_type: ${decoder_loss_type}
velocity_loss_lambda: 0.0