_target_: models.flow_matching_model.TimeFlowMatchingModel
image_size: ${img_size}
num_hist: ${num_hist}
num_pred: ${num_pred}
train_encoder: ${train_encoder}
train_predictor: ${train_predictor}
train_decoder: ${train_decoder}
decoder_loss_type: ${decoder_loss_type}
K: 4
normalize_flow: False
normalize_target: False
integrate_in_loss: False
use_pred_loss: False
integrator: "odeint_adjoint"
l2_reg_lambda: 0.0
tgt_type: "delta"
use_shortcut_loss: False
use_delta_tau: False
sigma_min: 0.0
integration_method: "euler"
horizon_length: ${horizon_length}
use_consistency_loss: False
step_combination: ${step_combination}