_target_: planning.gd.GDPlanner
horizon: 5
action_noise: 0.003
sample_type: 'randn' # 'zero' or 'randn'
lr: 1e-1 #1 
opt_steps: 1000
eval_every: 10
optimizer_type: "adam" # "sgd" or "adam"
max_grad_norm: 3.0
name: gd