name: memory_maze_7x7
args: []
kwargs: {}

dataset:
  _target_: "datasets.minigrid_dataset.load_minigrid_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/memory_maze/memory-maze-7x7-reset-two-traversals-chunked
  split_ratio: 0.9
  full_sequence: False
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}
  in_memory: False
  total_episodes: null
  proprio_available: True
  starts_with_noop_action: True

decoder_path: null
num_workers: 16 