_target_: models.vit.CacheMemoryViTPredictor
depth: 4
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
injection_type: "adamem"
zero_init: False
step_size: ${step_size}
shift_memory: False
both_injections: True
mem_layer_type: "all"
cache_size: ${num_hist}