_target_: models.vit.StateSpaceViTPredictor
depth: 2
heads: 16
mlp_dim: 512
dropout: 0.1
emb_dropout: 0
state_dim: 128
use_gate: False
dt_rank: 8
alpha_init: 0.1
injection_type: "adamem"
zero_init: False
step_size: ${step_size}
n_mem_blocks: ${n_mem_blocks}
shift_memory: False
both_injections: True
mem_layer_type: "all"