_target_: models.state_space_model.LinearStateSpaceModel

# Standard parameters (matching ViT interface)
num_patches: 196
num_frames: 16
dim: 384
depth: 6
heads: 16
mlp_dim: 2048
dim_head: 64
dropout: 0.1
emb_dropout: 0
pool: 'mean'

# State space specific parameters
state_dim: 384  # can be different from dim

# Additive control parameters
action_dim: 10  # match your action_emb_dim from train.yaml
