_target_: models.vit.LoRAInjectionViTPredictor
depth: 2
heads: 16
mlp_dim: 512
dropout: 0.1
emb_dropout: 0
state_dim: 128
dt_rank: 8
lora_rank: 8
lora_alpha: 2.0
gen_type: "A"
injection_type: "lora_qk"
step_size: ${step_size}
n_mem_blocks: ${n_mem_blocks}
shift_memory: True