_target_: models.vit.DynamicFFNVitPredictor
depth: 4
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
state_dim: 512
dt_rank: 128
ffn_rank: 64
gen_hidden_mul: 2
alpha_mem: 1.0
step_size: ${step_size}
n_mem_blocks: ${n_mem_blocks}
shift_memory: False
mem_layer_type: "all"