_target_: models.vit.MACViTPredictor
depth: 6
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
pool: 'mean'
n_persistent: 4
n_retrieved: 4
memory_module:
  _target_: models.memory.NeuralMemory
  hidden_scale: 2
  depth: 3
  eta: 0.9
  theta: 0.9
  alpha: 0.01