_target_: models.vit.MACViTPredictor
depth: 6
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
pool: 'mean'
n_persistent: 4
n_retrieved: 4
hidden_scale: 2
mem_depth: 3
mem_eta: 0.9
mem_theta: 0.1
mem_alpha: 0.01