_target_: models.vit.MACViTPredictor
depth: 6
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
pool: 'mean'
n_persistent: 1
hidden_scale: 2
mem_depth: 1
mem_eta: 0.01 # prev surprise decay
mem_theta: 1e-4 # memory update rate
mem_alpha: 0.01 # prev memory forget rate
max_grad_norm: 5.0 
momentum_clip: 2.0
weight_clip: 10.0
update_steps: 10
update_type: "selfattention"
proj_k_eq_q: False