_target_: models.vit.MAGViTPredictor
depth: 6
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
hidden_scale: 2
mem_depth: 1
mem_eta: 0.01
mem_theta: 1e-4
mem_alpha: 0.01
pool: "mean"
gate_type: "sigmoid"
use_residual: True