_target_: models.vit.StateSpaceViTPredictor
depth: 6
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
state_dim: 256
use_gate: False
dt_rank: 16
alpha_init: 0.1
injection_type: "misst"
step_size: ${step_size}
n_mem_blocks: ${n_mem_blocks}