_target_: models.vit.StateSpaceViTPredictor
depth: 4
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
state_dim: 512
use_gate: False
dt_rank: 128
alpha_init: 0.1
injection_type: "ca_basic"
use_cls_token: ${use_cls_token}
step_size: ${step_size}
n_mem_blocks: ${n_mem_blocks}
shift_memory: False
mem_layer_type: "all"