_target_: models.vit.SecondOrderViTPredictor
depth: 6
heads: 16
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0
pool: 'mean'
inner_dim: null
action_dim: ${action_emb_dim}
dt: 1.0
damping: -0.1
integration_method: "rk4"
integration_func: "odeint"
prior_scale: 1.0
integration_steps: 1
grad_ckpt: False
force_orthogonal: True
random_steps: False
base_frameskip: ${frameskip}