_target_: models.encoder.resnet.ResNetSmallTokens
in_ch: 3
stem_ch: 32
stages: [2, 2, 1]
channels: [32, 64, 128]
strides: [2, 2, 1]
norm: "gn"
emb_dim: 256
freeze_backbone: False
return_map: False
gn_groups: 32
